# -*- coding: utf-8 -*-
"""Face Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtSb4VrB1waR7Wkr_zqFb7MK2eGuRGqF
"""
"""
!pip install tensorflow==2.4.1 tensorflow-gpu==2.4.1 opencv-python matplotlib

!pip install tensorflow

!pip install opencv-python

!pip install matplotlib
"""

#Importovanje standardnih biblioteka
import cv2
import os
import random
import numpy as np
from matplotlib import pyplot as plt

#Importovanje tensorflow biblioteka - FUNCTIONAL API
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer, Conv2D, Dense, MaxPooling2D, Input, Flatten
import tensorflow as tf



#Ово значи да се могу подесити параметри да се постепено повећава коришћење GPU меморије током извршавања програма, како би се избегла грешка услед недостатка меморије.
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
  tf.config.experimental.set_memory_growth(gpu, True)

POS_PATH = os.path.join('data','positive')
NEG_PATH = os.path.join('data', 'negative')
ANC_PATH = os.path.join('data','anchorA')

os.makedirs(POS_PATH)
os.makedirs(NEG_PATH)
os.makedirs(ANC_PATH)

#Uncompress TAR GZ Labelled facces in the wild dataset
!tar -xf lfw.tgz

#Premestanje lfw slika u folder data/negative

for directory in os.listdir('lfw'):
  for file in os.listdir(os.path.join('lfw', directory)):
    EX_PATH = os.path.join('lfw', directory, file)
    NEW_PATH = os.path.join(NEG_PATH, file)
    os.replace(EX_PATH, NEW_PATH)


#Importovanje uuid biblioteke za generisanje jedinstvenih imena slika
import uuid

os.path.join(ANC_PATH,'{}.jpg'.format(uuid.uuid1()))

#Establish a connection to the webcam
cap = cv2.VideoCapture(1)
while cap.isOpened():
  ret, frame = cap.read()

  #Cut down frame to 250x250 pixels
  frame = frame[120:120+250,200:200+250, :]

  #Collect anchors
  if cv2.waitKey(1) & 0XFF == ord('a'):
    #Creating the unique file path
    imgname = os.path.join(ANC_PATH, '{}.jpg'.format(uuid.uuid1()))
    #Write out anchor image
    cv2.imwrite(imgname, frame)

  #Collect positives
  if cv2.waitKey(1) & 0XFF == ord('p'):
    #Creating unique file path
    imgname = os.path.join(POS_PATH, '{}.jpg'.format(uuid.uuid1()))
    #Write out positive image
    cv2.imwrite(imgname, frame)

  #Show image back to screen
  cv2.imshow('Image Collection', frame)

  #Breaking gracefully
  if cv2.waitKey(1) & 0XFF == ord('q'):
    break

#Release the webcam
cap.release()
#Close the image show frame
cv2.destroyAllWindows()
